#!/usr/bin/env python

import random, string, sys

max_len = 1024*2
choices = ' ' + string.ascii_letters + ' ' + string.digits + ' '

for l in range(max_len):
	s = '[%d] %s\n'%(l, ''.join(random.choice(choices) for x in range(l)))
	sys.stdout.write('STDOUT: %s\n'%(s))
	sys.stderr.write('STDERR: %s\n'%(s))
