#!/usr/bin/env python

import random, string

max_len = 2048
choices = ' ' + string.ascii_letters + ' ' + string.digits + ' '

for l in range(max_len):
	print '[%d]'%(l), ''.join(random.choice(choices) for x in range(l))
